import { NextIntlClientProvider, useMessages } from 'next-intl';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Vercel from '@/components/Vercel';
import type { Metadata } from 'next';
import { cn } from '@/lib/utils';

import '../globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const LocaleLayout = ({
  children,
  params: { locale },
}: Readonly<{ children: React.ReactNode; params: { locale: string } }>) => {
  const messages = useMessages();

  return (
    <html lang={locale} className="dark scroll-smooth">
      <body className={cn('w-screen overflow-x-hidden', inter.className)}>
        <div className="relative flex h-full min-h-screen w-full bg-background bg-grid-small-white/[0.2]">
          <div className="pointer-events-none absolute inset-0 flex bg-background [mask-image:radial-gradient(ellipse_at_center,transparent_40%,black)] md:[mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]"></div>
          <div className="overflow-x-hidden">
            <NextIntlClientProvider locale={locale} messages={messages}>
              {children}
            </NextIntlClientProvider>
          </div>
        </div>
        <Navbar />
        <Vercel />
      </body>
    </html>
  );
};

export default LocaleLayout;
